sudo: false
language: node_js
node_js:
  - 14 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - chmod +x xiaoheiwowo/xiaoheiwowo.github.io/deploy.sh
  - bash xiaoheiwowo/xiaoheiwowo.github.io/deploy.sh
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
